"""Build human-readable report from saved-file verification and inventory."""
import json
from pathlib import Path
P=Path(__file__).resolve().parents[1]
v=json.loads((P/'verification.json').read_text());m=json.loads((P/'replacement_manifest.json').read_text());inv=json.loads((P/'asset_inventory.json').read_text())
assert v['passed'], 'Do not finalize a failed package'
lines=['# Saved-file topology and clearance report','',f"Overall result: **PASS**. {len(v['topology'])} evaluated asset meshes; {sum(r['faces'] for r in v['topology']):,} evaluated polygons. All have zero non-manifold edges and zero degenerate faces.",'',f"All {len(v['patch_topology'])} patched context meshes are manifold. Source hash remains unchanged.",'','## Walking and operating clearance','','All routes use the approved layout\'s 0.34 m radius, 1.8 m high envelope. Distances below are from the sampled center path to the nearest evaluated convex footprint, not a claim of engine collision clearance.','', '| Route | Minimum distance | Margin beyond 340 mm radius | Closest component |','|---|---:|---:|---|']
for r in v['routes']:lines.append(f"| {r['name']} | {r['minimum_obstacle_distance_m']*1000:.1f} mm | {(r['minimum_obstacle_distance_m']-.34)*1000:.1f} mm | {r['nearest_object']} |")
lines += ['',f"{sum(r['samples'] for r in v['routes'])} path samples. All {len(v['floor_support'])} floor rays found the retained finished floor. All {len(v['screening'])} waiting-hall sightlines to the fixture targets were blocked by retained source walls.",'','The stall standing positions also clear the closed leaf while the outward swing moves away from the occupant. The source cubicles remain compact. Final engine collision must preserve the small gate margins; do not use over-sized box colliders on hardware.','','## Pivots and door poses','','World coordinates below are metres, Z up. All leaves are closed at frame 1 and at their working open angle at frame 40. The entrance axes sit behind the leaf planes, on the opening side, so the inner corners clear the shared wall.','', '| Pivot | World X, Y, Z | Leaf width | Open Z angle |','|---|---|---:|---:|']
for p in m['pivots']:lines.append(f"| {p['name']} | {', '.join(f'{x:.3f}' for x in p['position_world'])} | {p['width']:.3f} m | {p['open_degrees']:+.0f} degrees |")
lines += ['',f"{sum(len(r['sampled_degrees']) for r in v['swings'])} sampled door poses passed leaf/hardware-versus-fixed-geometry checks. The door sweep regions are mutually separated. Hinge mating pieces and the corresponding mechanical stop are intentional contacts and excluded from collision failure counts.",'', 'Both nominal 0.900 x 2.200 m openings passed 267 reveal rays each. Door leaves and hardware reduce the working passage locally; the radius checks above include that reduction.','','## Replacement and surface ownership','',f"{len(m['replacements'])} exact proxies are replaced; {len(inv)} asset objects are inventoried. The new closed rear cubicle panels, door assemblies and ancillary hardware are additions within the approved envelopes. No hall lockers, hall furniture or privacy-screen walls were changed.",'','See `replacement_manifest.json` for every original proxy, its replacement parts and the five opening-specific patches; `asset_inventory.json` provides dimensions, material slots, parent relationships and assembly matrices.','', 'The finished steel liners own the entrance reveals. The concealed wall boundaries are notched only below the recessed headers, leaving 4 mm separation behind the liners. Face trims cover the joints from both sides.','','## Limits','','Blender-only saved/reopened checks. No Unreal import, collision cook, PIE, accessibility certification or structural/plumbing engineering is claimed. The curved fixtures use closed shells and capped shared-vertex pipe meshes. Multiple physically connected components intentionally remain separate editable meshes.']
(P/'clearance_report.md').write_text('\n'.join(lines)+'\n')
# Complete group mapping: original replacements plus newly added assembly parts.
m['assembly_groups']={n:[r['name'] for r in inv if r['name'].startswith('PLR_'+n)] for n in ['Women_Entry','Men_Entry','Women_A','Women_B','Men_A','Women_Basin','Men_Basin','Men_Urinal']}
m['inventory']='asset_inventory.json';m['clearance_report']='clearance_report.md';m['references']='REFERENCES.md'
(P/'replacement_manifest.json').write_text(json.dumps(m,indent=2))

import struct,hashlib
views=json.loads((P/'previews/views_all.json').read_text());checks=[]
for view in views:
 f=P/'previews'/(view['name']+'.png');data=f.read_bytes();wh=struct.unpack('>II',data[16:24]);assert wh==(1200,900) and len(data)>10000
 checks.append(dict(file=f.name,size_pixels=wh,sha256=hashlib.sha256(data).hexdigest(),temporary_review_lighting=True))
(P/'render_verification.json').write_text(json.dumps(dict(passed=True,render_count=len(checks),images=checks),indent=2))
