import unreal,json
from pathlib import Path
out=Path(__file__).resolve().parents[1]/'revision10';root='/Game/MaldekRefinement/R10';lib=unreal.EditorAssetLibrary;ml=unreal.MaterialEditingLibrary;at=unreal.AssetToolsHelpers.get_asset_tools()
m=lib.load_asset(root+'/Materials/M_Flashlight_Optics') or at.create_asset('M_Flashlight_Optics',root+'/Materials',unreal.Material,unreal.MaterialFactoryNew());ml.delete_all_material_expressions(m);m.set_editor_property('material_domain',unreal.MaterialDomain.MD_LIGHT_FUNCTION)
uv=ml.create_material_expression(m,unreal.MaterialExpressionTextureCoordinate)
f=ml.create_material_expression(m,unreal.MaterialExpressionCustom);f.set_editor_property('output_type',unreal.CustomMaterialOutputType.CMOT_FLOAT1);ci=unreal.CustomInput();ci.set_editor_property('input_name','UV');f.set_editor_property('inputs',[ci])
f.set_editor_property('code','float2 p=(UV-0.5)*2.0; float r=length(p); float core=0.72*exp(-pow(r/0.24,4.0)); float spill=0.20*exp(-pow(r/0.67,2.0)); float corona=0.045*exp(-pow((r-0.38)/0.065,2.0)); float texture=1.0+0.018*sin(atan2(p.y,p.x)*12.0)*smoothstep(0.18,0.55,r); return saturate((core+spill+corona)*texture*(1.0-smoothstep(0.82,1.0,r)));')
ml.connect_material_expressions(uv,'',f,'UV');ml.connect_material_property(f,'',unreal.MaterialProperty.MP_EMISSIVE_COLOR);ml.recompile_material(m);lib.save_loaded_asset(m)
bp=lib.load_asset(root+'/BP_StationWalker') or lib.duplicate_asset('/Game/MaldekRefinement/R09/BP_StationWalker',root+'/BP_StationWalker');unreal.BlueprintEditorLibrary.compile_blueprint(bp)
light=unreal.get_default_object(bp.generated_class()).get_components_by_class(unreal.SpotLightComponent)[0];light.set_light_function_material(m);light.set_light_function_scale(unreal.Vector(1,1,1));light.set_intensity(.23);light.set_inner_cone_angle(0);light.set_outer_cone_angle(32);light.set_attenuation_radius(850);light.set_editor_property('light_function_fade_distance',10000.);light.set_editor_property('disabled_brightness',.25);lib.save_loaded_asset(bp,False)
gm=lib.load_asset(root+'/BP_StationWalkGameMode') or lib.duplicate_asset('/Game/MaldekRefinement/R09/BP_StationWalkGameMode',root+'/BP_StationWalkGameMode');unreal.get_default_object(gm.generated_class()).set_editor_property('default_pawn_class',bp.generated_class());lib.save_loaded_asset(gm,False)
world=unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world();assert world.get_name()=='BlockOut_R10';world.get_world_settings().set_editor_property('default_game_mode',gm.generated_class());assert unreal.get_editor_subsystem(unreal.LevelEditorSubsystem).save_current_level()
(out/'flashlight_setup.json').write_text(json.dumps({'beam':'hotspot, feathered spill, faint corona and reflector variation','lumens':.23,'outer_cone_degrees':32,'radius_cm':850,'material':m.get_path_name()},indent=2))
